version: '3.8'

volumes:
  modules:
  databaseData:

networks:
  internalDB:
  internalRedis:

services:
  SSHProxyDev:
    image: ssh-proxy:dev
    command: /bin/sh -c "while sleep 1000; do :; done"
    build:
      context: ./
      dockerfile: Dockerfile.dev
    volumes:
      # API Folders
      - ./:/workspace:cached
      - modules:/workspace/node_modules
    networks:
      - internalDB

  Database:
    image: postgres:alpine
    volumes:
      - databaseData:/var/lib/postgresql/data
    networks:
      - internalDB
    environment:
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: ssh-proxy

  Redis:
    image: redis:alpine3.12
    networks:
      - internalRedis
